/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 07299b3c73d1e7872282fb2b7323ce0f)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	DB: D1Database;
	MEMORY_INDEX: VectorizeIndex;
	AI: Ai;
	APP_ENV: "production";
	ALLOWED_GITHUB_USER_ID: "SET_YOUR_NUMERIC_GITHUB_ID";
	ALLOWED_GITHUB_LOGIN: "your-github-login";
	GITHUB_EXPORT_REPOSITORY: "your-github-login/ai-cloud-memory-backups";
	NATIVE_AUTOMATION_ENABLED: "false";
	PUBLIC_ORIGIN: "auto";
	SEMANTIC_SEARCH_ENABLED: "false";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "ALLOWED_GITHUB_USER_ID" | "ALLOWED_GITHUB_LOGIN" | "GITHUB_EXPORT_REPOSITORY" | "NATIVE_AUTOMATION_ENABLED" | "PUBLIC_ORIGIN" | "SEMANTIC_SEARCH_ENABLED">> {}
}
